//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeetABit.Binary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeetABit.Binary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an absolute path..
        /// </summary>
        internal static string Exception_Argument_AbsolutePath {
            get {
                return ResourceManager.GetString("Exception_Argument_AbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of LeetABit.Binary.LogicalPath type was expected..
        /// </summary>
        internal static string Exception_Argument_LogicalPathExpected {
            get {
                return ResourceManager.GetString("Exception_Argument_LogicalPathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified LeetABit.Binary.LogicalPath argument and current instance both have to be absolute or both relative..
        /// </summary>
        internal static string Exception_Argument_LogicalPathOfDifferentKind {
            get {
                return ResourceManager.GetString("Exception_Argument_LogicalPathOfDifferentKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result object represents a successfull operation..
        /// </summary>
        internal static string Exception_Argument_ResultSuccessfull {
            get {
                return ResourceManager.GetString("Exception_Argument_ResultSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be composed of white spaces only..
        /// </summary>
        internal static string Exception_Argument_WhiteSpace {
            get {
                return ResourceManager.GetString("Exception_Argument_WhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation allowed only for absolute path instance..
        /// </summary>
        internal static string Exception_InvalidOperation_AbsolutePath {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_AbsolutePath", resourceCulture);
            }
        }
    }
}
